version: "3"
#Source https://dev.to/titronium/clickhouse-server-in-1-minute-with-docker-4gf2

services:
  ch_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./devel/data/clickhouse:/var/lib/clickhouse
      - ./devel/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./devel/config.xml:/etc/clickhouse-server/config.d/config.xml
    networks:
        - ch_ntw

  ch_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
        - ch_ntw

networks:
  ch_ntw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24
